name: Build and push to TdA

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build
        uses: docker/build-push-action@v6.8.0
        with:
          context: ./
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: tda:latest
          outputs: type=docker,dest=/tmp/tda.tar

      - name: Upload to TdA
        uses: Tour-de-App/upload-app@tda-25
        with:
          team_token: eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJ2WElqUWxPd0x3OWsyUUZLY0JXWE1qbTN1Y29UZTlkNHVfZW9BeEI0bWk4In0.eyJleHAiOjE3NDc2MDQzMTQsImlhdCI6MTczNDY0NDMxNCwianRpIjoiYzYyNDVhNzQtYjE4OS00NGEwLTg2ZTQtMzJlZWEyMDUzY2U5IiwiaXNzIjoiaHR0cHM6Ly9rZXljbG9hay5yZWdpc3RyeS50b3VyZGUuYXBwL3JlYWxtcy90ZGFfdGVhbXMiLCJhdWQiOiJhY2NvdW50Iiwic3ViIjoiY2FkYmJhNzgtOTcyNi00MzYwLWJjNTctMTIyMjNkZmRhOTk5IiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiYXV0aGZpc2giLCJzaWQiOiI5YTQzNmVmOC01NTMzLTQ4YTktYjEzZS1jYzUzZWFkM2JiYjQiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbIi8qIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIiwiZGVmYXVsdC1yb2xlcy10ZGFfdGVhbXMiXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUgb2ZmbGluZV9hY2Nlc3MiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwibmFtZSI6Ik1hcmVrIE5pa2wiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJuaWtsbWFyZWsyM0Brb3NpbmthLmNvbSIsImdpdmVuX25hbWUiOiJNYXJlayIsImZhbWlseV9uYW1lIjoiTmlrbCIsImVtYWlsIjoibmlrbG1hcmVrMjNAa29zaW5rYS5jb20ifQ.RvaCl1DDFaKQsefVz-9z-KWq2gId3h-fKfMKoGZOZ1BTtgJ8Qo8PqoV3F9hji62dRN7FYt7VQC7HNycugva1Ai0KYZkoo9yAIH0-H-ZMcUHBko4RZEGdTIUIKLHqbLY0kPvaYWpgJ3X8dKL1wjr_Tz3DGuLn_JGllVbYODbu5Wf_Wm4C_A2YELkTwZ-X0AnJd6zUNvVMTfctHy6fkPPzyfbIQfDegiS16y0DqORnwScV1gxNqFKRt85CWLF5NGquGbkkjPB5tHrmaXnF2R8tkjXld9Td5KTnXMaBJ56ExatxOVBdr617AUrSL4mJmoSdkOg4b5scUy8fwnF6fORsqQ
          image_name: tda
          image_path: /tmp/tda.tar